import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_parquet("criteo-uplift-samples.parquet")

# Basic conversion table
summary = df.groupby("treatment").agg(users=("conversion", "count"), conversions=("conversion", "sum"))
summary["conversion_rate"] = summary["conversions"] / summary["users"]

# Looks like a conversion lift based on treatment, time to compute absolute and incremental lift
control = summary.loc[0, "conversion_rate"]
treatment = summary.loc[1, "conversion_rate"]

absolute_lift = treatment - control
relative_lift = absolute_lift / control

print(f"The Estimated Absolute Lift in Conversion Rate is: {absolute_lift:.4%}")
print(f"The Estimated Relative Lift in Conversion Rate is: {relative_lift:.2%}")

# First visualisation - looks like a lift in conversion rate
summary["conversion_rate"].plot(kind="bar")
plt.title("Conversion Rate: Control vs Treatment")
plt.ylabel("Rate")
plt.show()
plt.savefig("conversion_rates.png", dpi=300)

# Second visualisation - a bootstrap distribution of lift 
import numpy as np

def bootstrap_lift(df, n=100):
    lifts = []

    for _ in range(n):
        sample = df.sample(frac=1, replace=True)
        summary = sample.groupby("treatment")["conversion"].mean()
        lift = summary[1] - summary[0]
        lifts.append(lift)
    
    return np.array(lifts)

lifts = bootstrap_lift(df)

plt.hist(lifts, bins=30)
plt.title("Bootstrap Distribution of conversion lift")
plt.show()
plt.savefig("bootstrap_distribution_lift.png", dpi=300)

# My hypothesis is that the ads served (treatment) impacted the conversion rate. The null hypothesis is that the treatment had no effect.
# Finding the statistical significance using two-portion z-test

from statsmodels.stats.proportion import proportions_ztest

count = [summary.loc[1, "conversions"], summary.loc[0, "conversions"]]
nobs = [summary.loc[1, "users"], summary.loc[0, "users"]]

z_stat, p_value = proportions_ztest(count, nobs)

# Finding 95% Confidence Interval for Conversion Rate Lift

p1 = summary.loc[1, "conversion_rate"]  # treatment
p0 = summary.loc[0, "conversion_rate"]  # control

n1 = summary.loc[1, "users"]
n0 = summary.loc[0, "users"]

lift = p1 - p0
print(f"Absolute Lift is {lift}")

    # Find the Standard Error

standard_error = np.sqrt(
    (p1 * (1-p1)) / n1 +
    (p0 * (1-p0)) / n0
)
print(f"Standard Error is {standard_error}")

    # Picking 95% Confidence Interval & Build
z = 1.96
lower = lift - z * standard_error
upper = lift + z * standard_error
print(f"95% CI: [{lower:.6f}, {upper:.6f}]")

# Creating Final Experiment Summary
results = {
    "Control cvr": f"{p0:.2%}",
    "Treatment cvr": f"{p1:.2%}",
    "Absolute lift": f"{lift:.2%}",
    "Relative lift": f"{relative_lift:.2%}",
    "Z-stat": f"{z_stat:.4f}",
    "P-value": f"{p_value:.4f}",
    "95% CI lower": f"{lower:.3%}",
    "95% CI upper": f"{upper:.3%}",
}

results_df = pd.DataFrame.from_dict(results, orient="index", columns=["value"])
print(results_df)

results_df.to_csv("experiment_summary.csv")

# Now estimating incremental conversions & business impact. Taking the lift and multiplying by treatment population count

treatment_users = summary.loc[1, "users"]
incremental_conversions = absolute_lift * treatment_users
print(f"Estimated incremental conversions: {incremental_conversions:.0f}")

    # Assign an estimated AOV. Assuming value for illustrative purposes.
avg_order_value = 55
incremental_revenue = incremental_conversions * avg_order_value
print(f"With an AOV of £{avg_order_value}, the incremental revenue generated by treatment was £{incremental_revenue:.0f}")

